#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-shell-impatience
Version  : 43e4e0a1e0eeb334a2da5224ce3ab4fdddf4f1b2
Release  : 5
URL      : https://github.com/timbertson/gnome-shell-impatience/archive/43e4e0a1e0eeb334a2da5224ce3ab4fdddf4f1b2.tar.gz
Source0  : https://github.com/timbertson/gnome-shell-impatience/archive/43e4e0a1e0eeb334a2da5224ce3ab4fdddf4f1b2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0+
Requires: gnome-shell-impatience-data = %{version}-%{release}
Patch1: 0001-Provide-a-meaningful-Makefile.patch
Patch2: 0003-settings-Use-system-wide-glib-schemas.patch

%description
<img src="http://gfxmonk.net/dist/status/project/gnome-shell-impatience.png">
Speed up builtin gnome-shell animations.

%package data
Summary: data components for the gnome-shell-impatience package.
Group: Data

%description data
data components for the gnome-shell-impatience package.


%prep
%setup -q -n gnome-shell-impatience-43e4e0a1e0eeb334a2da5224ce3ab4fdddf4f1b2
cd %{_builddir}/gnome-shell-impatience-43e4e0a1e0eeb334a2da5224ce3ab4fdddf4f1b2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586230796
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1586230796
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.net.gfxmonk.impatience.gschema.xml
/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/extension.js
/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/metadata.json
/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/prefs.js
/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/settings.js
